-- ==============================================================================
-- ZINNIA 2026 — SIMPLIFIED REFACTORED DATABASE SCHEMA (PostgreSQL / Supabase)
-- Core Architecture:
-- 1. participants (Includes food_collected tracking)
-- 2. events (TECH and NON_TECH types + results_finalized flag)
-- 3. event_registrations (Tracks registrations, teams & 1st/2nd/3rd prize positions)
-- 4. attendance (Gate entry & event participation verification)
-- 5. admin_roles (Role-based access control)
--
-- REMOVED TABLES:
-- - food_distribution (Simplified into participant boolean flag)
-- - certificates (Dynamically generated by application based on attendance + position)
-- ==============================================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop legacy tables if they exist
DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS food_distribution CASCADE;

-- 2. Participants Table
CREATE TABLE IF NOT EXISTS participants (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  agent_id VARCHAR(32) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  college VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  year VARCHAR(10) NOT NULL,
  clearance_level VARCHAR(32) DEFAULT 'LEVEL 01' CHECK (clearance_level IN ('LEVEL 01', 'LEVEL 02', 'LEVEL 03')),
  status VARCHAR(32) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'FLAGGED')),
  qr_token VARCHAR(255) UNIQUE NOT NULL,
  registered_events TEXT[] DEFAULT '{}',
  
  -- Simplified Food Tracking (No separate food table)
  food_collected BOOLEAN DEFAULT FALSE,
  food_collected_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_participants_agent_id ON participants(agent_id);
CREATE INDEX IF NOT EXISTS idx_participants_email ON participants(email);
CREATE INDEX IF NOT EXISTS idx_participants_qr_token ON participants(qr_token);

ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public participant registration" ON participants;
CREATE POLICY "Public participant registration" ON participants FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public participant read" ON participants;
CREATE POLICY "Public participant read" ON participants FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public participant update" ON participants;
CREATE POLICY "Public participant update" ON participants FOR UPDATE USING (true);

-- 3. Events Table (TECH and NON_TECH)
CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(64) PRIMARY KEY,
  code VARCHAR(16) NOT NULL,
  mission_name VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  event_type VARCHAR(16) NOT NULL CHECK (event_type IN ('TECH', 'NON_TECH')),
  category VARCHAR(32) NOT NULL,
  clearance_level VARCHAR(32) NOT NULL CHECK (clearance_level IN ('LEVEL 01', 'LEVEL 02', 'LEVEL 03')),
  team_size_min INTEGER DEFAULT 1,
  team_size_max INTEGER DEFAULT 1,
  is_single_event_only BOOLEAN DEFAULT FALSE,
  schedule_time VARCHAR(64) NOT NULL,
  duration VARCHAR(64) NOT NULL,
  venue VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  rules TEXT[] DEFAULT '{}',
  status VARCHAR(32) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'IN_PROGRESS', 'COMPLETED', 'LOCKED')),
  
  -- Results Finalization Control
  results_finalized BOOLEAN DEFAULT FALSE,
  results_finalized_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read events" ON events;
CREATE POLICY "Public read events" ON events FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin modify events" ON events;
CREATE POLICY "Admin modify events" ON events FOR ALL USING (true);

-- 4. Event Registrations & Prize Positions Table
-- Supports individual participants and team-based prize mapping
CREATE TABLE IF NOT EXISTS event_registrations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id VARCHAR(64) REFERENCES events(id) ON DELETE CASCADE,
  participant_id UUID REFERENCES participants(id) ON DELETE CASCADE,
  team_id VARCHAR(64),
  team_name VARCHAR(255),
  
  -- Result Position: 1 = 1st Prize, 2 = 2nd Prize, 3 = 3rd Prize, NULL = Participated
  position INTEGER CHECK (position IN (1, 2, 3) OR position IS NULL),
  
  registered_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_participant_per_event UNIQUE(event_id, participant_id)
);

CREATE INDEX IF NOT EXISTS idx_er_event_participant ON event_registrations(event_id, participant_id);
CREATE INDEX IF NOT EXISTS idx_er_team ON event_registrations(event_id, team_name);
CREATE INDEX IF NOT EXISTS idx_er_position ON event_registrations(event_id, position);

ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public event registrations insert" ON event_registrations;
CREATE POLICY "Public event registrations insert" ON event_registrations FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public event registrations read" ON event_registrations;
CREATE POLICY "Public event registrations read" ON event_registrations FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin event registrations update" ON event_registrations;
CREATE POLICY "Admin event registrations update" ON event_registrations FOR ALL USING (true);

-- 5. Attendance & Station Check-ins Table
-- Used to confirm actual event participation before certificates can be generated
CREATE TABLE IF NOT EXISTS attendance (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  participant_id UUID REFERENCES participants(id) ON DELETE CASCADE,
  agent_id VARCHAR(32) NOT NULL,
  checkin_type VARCHAR(32) NOT NULL CHECK (checkin_type IN ('ENTRY', 'EVENT')),
  event_id VARCHAR(64) REFERENCES events(id) ON DELETE SET NULL,
  scanned_by VARCHAR(255) NOT NULL,
  scanned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  location VARCHAR(255),
  CONSTRAINT unique_entry_per_participant UNIQUE(participant_id, checkin_type, event_id)
);

CREATE INDEX IF NOT EXISTS idx_att_agent_id ON attendance(agent_id);
CREATE INDEX IF NOT EXISTS idx_att_checkin_type ON attendance(checkin_type);
CREATE INDEX IF NOT EXISTS idx_att_event_participation ON attendance(participant_id, event_id);

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public attendance insert" ON attendance;
CREATE POLICY "Public attendance insert" ON attendance FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public attendance read" ON attendance;
CREATE POLICY "Public attendance read" ON attendance FOR SELECT USING (true);

-- 6. Admin Roles Table
CREATE TABLE IF NOT EXISTS admin_roles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL,
  role VARCHAR(64) NOT NULL CHECK (role IN ('SUPER_ADMIN', 'EVENT_ADMIN', 'ENTRY_STAFF', 'FOOD_STAFF', 'CERTIFICATE_ADMIN')),
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  granted_by VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_id ON admin_roles(user_id);

ALTER TABLE admin_roles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public admin roles read" ON admin_roles;
CREATE POLICY "Public admin roles read" ON admin_roles FOR SELECT USING (true);

-- ==============================================================================
-- 7. POPULATE 9 OFFICIAL SYMPOSIUM MISSIONS (TECH & NON-TECH)
-- ==============================================================================
INSERT INTO events (id, code, mission_name, title, event_type, category, clearance_level, team_size_min, team_size_max, is_single_event_only, schedule_time, duration, venue, description)
VALUES 
-- TECH EVENTS
('msn-sys-recovery', 'MSN-01', 'Operation: System Recovery', 'Debugging', 'TECH', 'TECHNICAL', 'LEVEL 01', 1, 2, FALSE, '10:00 AM - 10:45 AM', '1 hr', 'Cyber Lab 01', 'Debugging critical syntax, memory, and logical faults across fractured codebases.'),
('msn-oracle', 'MSN-02', 'Operation: ORACLE', 'AI Event', 'TECH', 'TECHNICAL', 'LEVEL 02', 1, 2, FALSE, '11:15 AM - 12:15 PM', '1 hr', 'AI Arena', 'Prompt engineering, neural lattice anomaly diagnosis, and model hallucination repair.'),
('msn-broken-records', 'MSN-03', 'Operation: Broken Records', 'Lost in SQL', 'TECH', 'TECHNICAL', 'LEVEL 01', 1, 2, FALSE, '12:30 PM - 01:30 PM', '1 hr', 'Database Lab', 'SQL recovery across fractured relational archives and corrupted database schemas.'),
('msn-infinity-protocol', 'MSN-04', 'Operation: Infinity Protocol', 'Infinity Challenge (Single event)', 'TECH', 'TECHNICAL', 'LEVEL 03', 2, 3, TRUE, '10:00 AM - 01:30 PM', '3 hrs 30 mins', 'Main Innovation Center', 'Multi-stage marathon of algorithms, logical decryption, and systemic survival.'),
('msn-mission-control', 'MSN-05', 'Operation: Mission Control', 'UI/UX Design (Single event)', 'TECH', 'TECHNICAL', 'LEVEL 02', 1, 2, TRUE, '10:30 AM - 01:00 PM', '2 hr 30 mins', 'Design Studio', 'Designing futuristic CHRONOS temporal incident interfaces and mission dashboards.'),

-- NON-TECH EVENTS
('msn-borderland-gce', 'MSN-06', 'Borderland at GCE', 'Borderland at GCE', 'NON_TECH', 'NON_TECHNICAL', 'LEVEL 01', 2, 4, FALSE, '10:45 AM - 01:00 PM', '2 hrs 15 minutes', 'Campus Quadrangle', 'Physical campus puzzle survival and timeline escape across university checkpoints.'),
('msn-think-strike-win', 'MSN-07', 'Think, Strike and Win', 'Think, Strike and Win', 'NON_TECH', 'NON_TECHNICAL', 'LEVEL 01', 2, 3, FALSE, '11:00 AM - 12:00 PM', '1 hr', 'Seminar Hall B', 'Fast-paced buzzer quiz, lateral reasoning, and rapid-response tactical thinking.'),
('msn-plot-twist', 'MSN-08', 'Plot Twist', 'Plot Twist', 'NON_TECH', 'NON_TECHNICAL', 'LEVEL 01', 1, 2, FALSE, '12:00 PM - 01:00 PM', '1 hr', 'Media Studio', 'Impromptu creative story development, roleplay, and temporal narrative presentation.'),
('msn-short-film', 'MSN-09', 'Short Film', 'Short Film', 'NON_TECH', 'NON_TECHNICAL', 'LEVEL 01', 1, 5, FALSE, '12:30 PM - 01:00 PM', '30 minutes', 'Auditorium Screen 01', 'Original film screening celebrating sci-fi, temporal anomalies, and AI breakthroughs.')
ON CONFLICT (id) DO UPDATE SET 
  mission_name = EXCLUDED.mission_name,
  event_type = EXCLUDED.event_type,
  description = EXCLUDED.description,
  schedule_time = EXCLUDED.schedule_time;
